-- ============================================================
-- DEPRECATED: This file is replaced by migrations/001_idempotent_seed.sql
-- ============================================================
-- Please run: database/migrations/001_idempotent_seed.sql instead
-- That file uses MERGE statements and is safe to re-run.
-- ============================================================
