-- ============================================================
-- ALTONSHOTEL Management System
-- Idempotent Seed Data Version: 001
-- Description: Full workflow test data using MERGE statements
--              Safe to re-run without errors
-- Password for all test users: Admin123!
-- ============================================================

-- ============================================================
-- ROLES (required before users)
-- ============================================================
MERGE INTO ROLES t
USING (SELECT 'ADMIN' AS ROLE_NAME, 'Full system access' AS DESCRIPTION FROM DUAL) s
ON (t.ROLE_NAME = s.ROLE_NAME)
WHEN NOT MATCHED THEN
    INSERT (ROLE_NAME, DESCRIPTION) VALUES (s.ROLE_NAME, s.DESCRIPTION);

MERGE INTO ROLES t
USING (SELECT 'RECEPTIONIST' AS ROLE_NAME, 'Front desk operations' AS DESCRIPTION FROM DUAL) s
ON (t.ROLE_NAME = s.ROLE_NAME)
WHEN NOT MATCHED THEN
    INSERT (ROLE_NAME, DESCRIPTION) VALUES (s.ROLE_NAME, s.DESCRIPTION);

MERGE INTO ROLES t
USING (SELECT 'MANAGER' AS ROLE_NAME, 'Reports and oversight' AS DESCRIPTION FROM DUAL) s
ON (t.ROLE_NAME = s.ROLE_NAME)
WHEN NOT MATCHED THEN
    INSERT (ROLE_NAME, DESCRIPTION) VALUES (s.ROLE_NAME, s.DESCRIPTION);

-- ============================================================
-- ROOM TYPES
-- ============================================================
MERGE INTO ROOM_TYPES t
USING (SELECT 'Standard' AS TYPE_NAME, 'Standard single room with basic amenities' AS DESCRIPTION, 80.00 AS BASE_PRICE, 2 AS MAX_OCCUPANCY FROM DUAL) s
ON (t.TYPE_NAME = s.TYPE_NAME)
WHEN NOT MATCHED THEN
    INSERT (TYPE_NAME, DESCRIPTION, BASE_PRICE, MAX_OCCUPANCY) VALUES (s.TYPE_NAME, s.DESCRIPTION, s.BASE_PRICE, s.MAX_OCCUPANCY);

MERGE INTO ROOM_TYPES t
USING (SELECT 'Deluxe' AS TYPE_NAME, 'Spacious room with premium amenities' AS DESCRIPTION, 150.00 AS BASE_PRICE, 2 AS MAX_OCCUPANCY FROM DUAL) s
ON (t.TYPE_NAME = s.TYPE_NAME)
WHEN NOT MATCHED THEN
    INSERT (TYPE_NAME, DESCRIPTION, BASE_PRICE, MAX_OCCUPANCY) VALUES (s.TYPE_NAME, s.DESCRIPTION, s.BASE_PRICE, s.MAX_OCCUPANCY);

MERGE INTO ROOM_TYPES t
USING (SELECT 'Suite' AS TYPE_NAME, 'Luxury suite with separate living area' AS DESCRIPTION, 250.00 AS BASE_PRICE, 4 AS MAX_OCCUPANCY FROM DUAL) s
ON (t.TYPE_NAME = s.TYPE_NAME)
WHEN NOT MATCHED THEN
    INSERT (TYPE_NAME, DESCRIPTION, BASE_PRICE, MAX_OCCUPANCY) VALUES (s.TYPE_NAME, s.DESCRIPTION, s.BASE_PRICE, s.MAX_OCCUPANCY);

MERGE INTO ROOM_TYPES t
USING (SELECT 'Presidential' AS TYPE_NAME, 'Top-floor suite with panoramic views' AS DESCRIPTION, 500.00 AS BASE_PRICE, 4 AS MAX_OCCUPANCY FROM DUAL) s
ON (t.TYPE_NAME = s.TYPE_NAME)
WHEN NOT MATCHED THEN
    INSERT (TYPE_NAME, DESCRIPTION, BASE_PRICE, MAX_OCCUPANCY) VALUES (s.TYPE_NAME, s.DESCRIPTION, s.BASE_PRICE, s.MAX_OCCUPANCY);

-- ============================================================
-- USERS
-- Password hash generated via: RAWTOHEX(DBMS_CRYPTO.HASH(UTL_RAW.CAST_TO_RAW('Admin123!'), DBMS_CRYPTO.HASH_SH256))
-- ============================================================
MERGE INTO USERS t
USING (
    SELECT 'admin' AS USERNAME,
           RAWTOHEX(DBMS_CRYPTO.HASH(UTL_RAW.CAST_TO_RAW('Admin123!'), DBMS_CRYPTO.HASH_SH256)) AS PASSWORD_HASH,
           'System Administrator' AS FULL_NAME,
           'admin@altonshotel.com' AS EMAIL,
           1 AS ROLE_ID,
           1 AS IS_ACTIVE
    FROM DUAL
) s
ON (t.USERNAME = s.USERNAME)
WHEN NOT MATCHED THEN
    INSERT (USERNAME, PASSWORD_HASH, FULL_NAME, EMAIL, ROLE_ID, IS_ACTIVE)
    VALUES (s.USERNAME, s.PASSWORD_HASH, s.FULL_NAME, s.EMAIL, s.ROLE_ID, s.IS_ACTIVE);

MERGE INTO USERS t
USING (
    SELECT 'reception1' AS USERNAME,
           RAWTOHEX(DBMS_CRYPTO.HASH(UTL_RAW.CAST_TO_RAW('Admin123!'), DBMS_CRYPTO.HASH_SH256)) AS PASSWORD_HASH,
           'Jane Smith' AS FULL_NAME,
           'jane.smith@altonshotel.com' AS EMAIL,
           2 AS ROLE_ID,
           1 AS IS_ACTIVE
    FROM DUAL
) s
ON (t.USERNAME = s.USERNAME)
WHEN NOT MATCHED THEN
    INSERT (USERNAME, PASSWORD_HASH, FULL_NAME, EMAIL, ROLE_ID, IS_ACTIVE)
    VALUES (s.USERNAME, s.PASSWORD_HASH, s.FULL_NAME, s.EMAIL, s.ROLE_ID, s.IS_ACTIVE);

MERGE INTO USERS t
USING (
    SELECT 'manager1' AS USERNAME,
           RAWTOHEX(DBMS_CRYPTO.HASH(UTL_RAW.CAST_TO_RAW('Admin123!'), DBMS_CRYPTO.HASH_SH256)) AS PASSWORD_HASH,
           'Robert Johnson' AS FULL_NAME,
           'robert.j@altonshotel.com' AS EMAIL,
           3 AS ROLE_ID,
           1 AS IS_ACTIVE
    FROM DUAL
) s
ON (t.USERNAME = s.USERNAME)
WHEN NOT MATCHED THEN
    INSERT (USERNAME, PASSWORD_HASH, FULL_NAME, EMAIL, ROLE_ID, IS_ACTIVE)
    VALUES (s.USERNAME, s.PASSWORD_HASH, s.FULL_NAME, s.EMAIL, s.ROLE_ID, s.IS_ACTIVE);

-- ============================================================
-- ROOMS
-- ============================================================
MERGE INTO ROOMS t
USING (SELECT '101' AS ROOM_NUMBER, 1 AS TYPE_ID, 1 AS FLOOR, 'AVAILABLE' AS STATUS, 'Ground floor standard room, garden view' AS DESCRIPTION FROM DUAL) s
ON (t.ROOM_NUMBER = s.ROOM_NUMBER)
WHEN NOT MATCHED THEN
    INSERT (ROOM_NUMBER, TYPE_ID, FLOOR, STATUS, DESCRIPTION) VALUES (s.ROOM_NUMBER, s.TYPE_ID, s.FLOOR, s.STATUS, s.DESCRIPTION);

MERGE INTO ROOMS t
USING (SELECT '102' AS ROOM_NUMBER, 1 AS TYPE_ID, 1 AS FLOOR, 'AVAILABLE' AS STATUS, 'Ground floor standard room' AS DESCRIPTION FROM DUAL) s
ON (t.ROOM_NUMBER = s.ROOM_NUMBER)
WHEN NOT MATCHED THEN
    INSERT (ROOM_NUMBER, TYPE_ID, FLOOR, STATUS, DESCRIPTION) VALUES (s.ROOM_NUMBER, s.TYPE_ID, s.FLOOR, s.STATUS, s.DESCRIPTION);

MERGE INTO ROOMS t
USING (SELECT '103' AS ROOM_NUMBER, 1 AS TYPE_ID, 1 AS FLOOR, 'MAINTENANCE' AS STATUS, 'Ground floor standard room, under renovation' AS DESCRIPTION FROM DUAL) s
ON (t.ROOM_NUMBER = s.ROOM_NUMBER)
WHEN NOT MATCHED THEN
    INSERT (ROOM_NUMBER, TYPE_ID, FLOOR, STATUS, DESCRIPTION) VALUES (s.ROOM_NUMBER, s.TYPE_ID, s.FLOOR, s.STATUS, s.DESCRIPTION);

MERGE INTO ROOMS t
USING (SELECT '201' AS ROOM_NUMBER, 1 AS TYPE_ID, 2 AS FLOOR, 'AVAILABLE' AS STATUS, 'Second floor standard room' AS DESCRIPTION FROM DUAL) s
ON (t.ROOM_NUMBER = s.ROOM_NUMBER)
WHEN NOT MATCHED THEN
    INSERT (ROOM_NUMBER, TYPE_ID, FLOOR, STATUS, DESCRIPTION) VALUES (s.ROOM_NUMBER, s.TYPE_ID, s.FLOOR, s.STATUS, s.DESCRIPTION);

MERGE INTO ROOMS t
USING (SELECT '202' AS ROOM_NUMBER, 1 AS TYPE_ID, 2 AS FLOOR, 'AVAILABLE' AS STATUS, 'Second floor standard room, corner' AS DESCRIPTION FROM DUAL) s
ON (t.ROOM_NUMBER = s.ROOM_NUMBER)
WHEN NOT MATCHED THEN
    INSERT (ROOM_NUMBER, TYPE_ID, FLOOR, STATUS, DESCRIPTION) VALUES (s.ROOM_NUMBER, s.TYPE_ID, s.FLOOR, s.STATUS, s.DESCRIPTION);

MERGE INTO ROOMS t
USING (SELECT '301' AS ROOM_NUMBER, 2 AS TYPE_ID, 3 AS FLOOR, 'AVAILABLE' AS STATUS, 'Deluxe room with city view' AS DESCRIPTION FROM DUAL) s
ON (t.ROOM_NUMBER = s.ROOM_NUMBER)
WHEN NOT MATCHED THEN
    INSERT (ROOM_NUMBER, TYPE_ID, FLOOR, STATUS, DESCRIPTION) VALUES (s.ROOM_NUMBER, s.TYPE_ID, s.FLOOR, s.STATUS, s.DESCRIPTION);

MERGE INTO ROOMS t
USING (SELECT '302' AS ROOM_NUMBER, 2 AS TYPE_ID, 3 AS FLOOR, 'AVAILABLE' AS STATUS, 'Deluxe room with balcony' AS DESCRIPTION FROM DUAL) s
ON (t.ROOM_NUMBER = s.ROOM_NUMBER)
WHEN NOT MATCHED THEN
    INSERT (ROOM_NUMBER, TYPE_ID, FLOOR, STATUS, DESCRIPTION) VALUES (s.ROOM_NUMBER, s.TYPE_ID, s.FLOOR, s.STATUS, s.DESCRIPTION);

MERGE INTO ROOMS t
USING (SELECT '303' AS ROOM_NUMBER, 2 AS TYPE_ID, 3 AS FLOOR, 'AVAILABLE' AS STATUS, 'Deluxe room, premium amenities' AS DESCRIPTION FROM DUAL) s
ON (t.ROOM_NUMBER = s.ROOM_NUMBER)
WHEN NOT MATCHED THEN
    INSERT (ROOM_NUMBER, TYPE_ID, FLOOR, STATUS, DESCRIPTION) VALUES (s.ROOM_NUMBER, s.TYPE_ID, s.FLOOR, s.STATUS, s.DESCRIPTION);

MERGE INTO ROOMS t
USING (SELECT '401' AS ROOM_NUMBER, 2 AS TYPE_ID, 4 AS FLOOR, 'AVAILABLE' AS STATUS, 'Deluxe room, corner unit' AS DESCRIPTION FROM DUAL) s
ON (t.ROOM_NUMBER = s.ROOM_NUMBER)
WHEN NOT MATCHED THEN
    INSERT (ROOM_NUMBER, TYPE_ID, FLOOR, STATUS, DESCRIPTION) VALUES (s.ROOM_NUMBER, s.TYPE_ID, s.FLOOR, s.STATUS, s.DESCRIPTION);

MERGE INTO ROOMS t
USING (SELECT '402' AS ROOM_NUMBER, 2 AS TYPE_ID, 4 AS FLOOR, 'AVAILABLE' AS STATUS, 'Deluxe room, recently renovated' AS DESCRIPTION FROM DUAL) s
ON (t.ROOM_NUMBER = s.ROOM_NUMBER)
WHEN NOT MATCHED THEN
    INSERT (ROOM_NUMBER, TYPE_ID, FLOOR, STATUS, DESCRIPTION) VALUES (s.ROOM_NUMBER, s.TYPE_ID, s.FLOOR, s.STATUS, s.DESCRIPTION);

MERGE INTO ROOMS t
USING (SELECT '501' AS ROOM_NUMBER, 3 AS TYPE_ID, 5 AS FLOOR, 'AVAILABLE' AS STATUS, 'Suite with separate living area' AS DESCRIPTION FROM DUAL) s
ON (t.ROOM_NUMBER = s.ROOM_NUMBER)
WHEN NOT MATCHED THEN
    INSERT (ROOM_NUMBER, TYPE_ID, FLOOR, STATUS, DESCRIPTION) VALUES (s.ROOM_NUMBER, s.TYPE_ID, s.FLOOR, s.STATUS, s.DESCRIPTION);

MERGE INTO ROOMS t
USING (SELECT '502' AS ROOM_NUMBER, 3 AS TYPE_ID, 5 AS FLOOR, 'AVAILABLE' AS STATUS, 'Suite with kitchenette' AS DESCRIPTION FROM DUAL) s
ON (t.ROOM_NUMBER = s.ROOM_NUMBER)
WHEN NOT MATCHED THEN
    INSERT (ROOM_NUMBER, TYPE_ID, FLOOR, STATUS, DESCRIPTION) VALUES (s.ROOM_NUMBER, s.TYPE_ID, s.FLOOR, s.STATUS, s.DESCRIPTION);

MERGE INTO ROOMS t
USING (SELECT '601' AS ROOM_NUMBER, 3 AS TYPE_ID, 6 AS FLOOR, 'AVAILABLE' AS STATUS, 'Executive suite' AS DESCRIPTION FROM DUAL) s
ON (t.ROOM_NUMBER = s.ROOM_NUMBER)
WHEN NOT MATCHED THEN
    INSERT (ROOM_NUMBER, TYPE_ID, FLOOR, STATUS, DESCRIPTION) VALUES (s.ROOM_NUMBER, s.TYPE_ID, s.FLOOR, s.STATUS, s.DESCRIPTION);

MERGE INTO ROOMS t
USING (SELECT '602' AS ROOM_NUMBER, 4 AS TYPE_ID, 6 AS FLOOR, 'AVAILABLE' AS STATUS, 'Presidential suite, panoramic views' AS DESCRIPTION FROM DUAL) s
ON (t.ROOM_NUMBER = s.ROOM_NUMBER)
WHEN NOT MATCHED THEN
    INSERT (ROOM_NUMBER, TYPE_ID, FLOOR, STATUS, DESCRIPTION) VALUES (s.ROOM_NUMBER, s.TYPE_ID, s.FLOOR, s.STATUS, s.DESCRIPTION);

-- ============================================================
-- GUESTS
-- ============================================================
MERGE INTO GUESTS t
USING (SELECT 'John' AS FIRST_NAME, 'Doe' AS LAST_NAME, 'john.doe@email.com' AS EMAIL, '+1-555-0101' AS PHONE, 'PASSPORT' AS ID_TYPE, 'P12345678' AS ID_NUMBER, '123 Main St, New York, NY' AS ADDRESS, 'American' AS NATIONALITY FROM DUAL) s
ON (t.ID_NUMBER = s.ID_NUMBER)
WHEN NOT MATCHED THEN
    INSERT (FIRST_NAME, LAST_NAME, EMAIL, PHONE, ID_TYPE, ID_NUMBER, ADDRESS, NATIONALITY)
    VALUES (s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PHONE, s.ID_TYPE, s.ID_NUMBER, s.ADDRESS, s.NATIONALITY);

MERGE INTO GUESTS t
USING (SELECT 'Maria' AS FIRST_NAME, 'Garcia' AS LAST_NAME, 'maria.g@email.com' AS EMAIL, '+34-612-345678' AS PHONE, 'NATIONAL_ID' AS ID_TYPE, 'ES987654' AS ID_NUMBER, '45 Calle Mayor, Madrid' AS ADDRESS, 'Spanish' AS NATIONALITY FROM DUAL) s
ON (t.ID_NUMBER = s.ID_NUMBER)
WHEN NOT MATCHED THEN
    INSERT (FIRST_NAME, LAST_NAME, EMAIL, PHONE, ID_TYPE, ID_NUMBER, ADDRESS, NATIONALITY)
    VALUES (s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PHONE, s.ID_TYPE, s.ID_NUMBER, s.ADDRESS, s.NATIONALITY);

MERGE INTO GUESTS t
USING (SELECT 'Takeshi' AS FIRST_NAME, 'Yamamoto' AS LAST_NAME, 'takeshi.y@email.com' AS EMAIL, '+81-90-1234-5678' AS PHONE, 'PASSPORT' AS ID_TYPE, 'JP112233' AS ID_NUMBER, '1-1 Shibuya, Tokyo' AS ADDRESS, 'Japanese' AS NATIONALITY FROM DUAL) s
ON (t.ID_NUMBER = s.ID_NUMBER)
WHEN NOT MATCHED THEN
    INSERT (FIRST_NAME, LAST_NAME, EMAIL, PHONE, ID_TYPE, ID_NUMBER, ADDRESS, NATIONALITY)
    VALUES (s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PHONE, s.ID_TYPE, s.ID_NUMBER, s.ADDRESS, s.NATIONALITY);

MERGE INTO GUESTS t
USING (SELECT 'Sarah' AS FIRST_NAME, 'Johnson' AS LAST_NAME, 'sarah.j@email.com' AS EMAIL, '+44-7700-900123' AS PHONE, 'DRIVERS_LICENSE' AS ID_TYPE, 'UK445566' AS ID_NUMBER, '10 Oxford St, London' AS ADDRESS, 'British' AS NATIONALITY FROM DUAL) s
ON (t.ID_NUMBER = s.ID_NUMBER)
WHEN NOT MATCHED THEN
    INSERT (FIRST_NAME, LAST_NAME, EMAIL, PHONE, ID_TYPE, ID_NUMBER, ADDRESS, NATIONALITY)
    VALUES (s.FIRST_NAME, s.LAST_NAME, s.EMAIL, s.PHONE, s.ID_TYPE, s.ID_NUMBER, s.ADDRESS, s.NATIONALITY);

-- ============================================================
-- SAMPLE WORKFLOW DATA
-- Uses anonymous blocks with variables to dynamically resolve IDs
-- ============================================================
DECLARE
    v_admin_id NUMBER;
    v_recep_id NUMBER;
    v_guest1_id NUMBER;
    v_guest2_id NUMBER;
    v_guest3_id NUMBER;
    v_room_201_id NUMBER;
    v_room_301_id NUMBER;
    v_room_501_id NUMBER;
    v_reservation1_id NUMBER;
    v_reservation2_id NUMBER;
    v_reservation3_id NUMBER;
    v_booking1_id NUMBER;
    v_booking2_id NUMBER;
    v_booking3_id NUMBER;
    v_checkin1_id NUMBER;
    v_invoice1_id NUMBER;
    v_invoice2_id NUMBER;
    v_payment1_id NUMBER;
BEGIN
    -- Resolve user IDs
    SELECT USER_ID INTO v_admin_id FROM USERS WHERE USERNAME = 'admin';
    SELECT USER_ID INTO v_recep_id FROM USERS WHERE USERNAME = 'reception1';

    -- Resolve guest IDs
    SELECT GUEST_ID INTO v_guest1_id FROM GUESTS WHERE ID_NUMBER = 'P12345678';
    SELECT GUEST_ID INTO v_guest2_id FROM GUESTS WHERE ID_NUMBER = 'ES987654';
    SELECT GUEST_ID INTO v_guest3_id FROM GUESTS WHERE ID_NUMBER = 'JP112233';

    -- Resolve room IDs
    SELECT ROOM_ID INTO v_room_201_id FROM ROOMS WHERE ROOM_NUMBER = '201';
    SELECT ROOM_ID INTO v_room_301_id FROM ROOMS WHERE ROOM_NUMBER = '301';
    SELECT ROOM_ID INTO v_room_501_id FROM ROOMS WHERE ROOM_NUMBER = '501';

    -- ============================================================
    -- SCENARIO 1: Completed workflow (John Doe - 3 night stay)
    -- Reservation -> Booking -> Check-in -> Invoice -> Payment -> Check-out
    -- ============================================================
    BEGIN
        INSERT INTO RESERVATIONS (GUEST_ID, ROOM_TYPE_ID, CHECK_IN_DATE, CHECK_OUT_DATE, STATUS, SPECIAL_REQUESTS, CREATED_BY)
        VALUES (v_guest1_id, 1, SYSDATE - 5, SYSDATE - 2, 'COMPLETED', 'Non-smoking room preferred', v_recep_id)
        RETURNING RESERVATION_ID INTO v_reservation1_id;

        INSERT INTO BOOKINGS (RESERVATION_ID, ROOM_ID, CHECK_IN_DATE, CHECK_OUT_DATE, RATE_PER_NIGHT, STATUS)
        VALUES (v_reservation1_id, v_room_201_id, SYSDATE - 5, SYSDATE - 2, 80.00, 'COMPLETED')
        RETURNING BOOKING_ID INTO v_booking1_id;

        INSERT INTO CHECKINS (BOOKING_ID, CHECKED_IN_BY, NOTES)
        VALUES (v_booking1_id, v_recep_id, 'Guest arrived on time, passport verified')
        RETURNING CHECKIN_ID INTO v_checkin1_id;

        INSERT INTO CHECKOUTS (CHECKIN_ID, CHECKED_OUT_BY, NOTES)
        VALUES (v_checkin1_id, v_recep_id, 'Guest satisfied, paid in full');

        INSERT INTO INVOICES (BOOKING_ID, GUEST_ID, STATUS)
        VALUES (v_booking1_id, v_guest1_id, 'PAID')
        RETURNING INVOICE_ID INTO v_invoice1_id;

        INSERT INTO INVOICE_ITEMS (INVOICE_ID, DESCRIPTION, QUANTITY, UNIT_PRICE)
        VALUES (v_invoice1_id, 'Room 201 - Standard (3 nights)', 1, 240.00);

        INSERT INTO INVOICE_ITEMS (INVOICE_ID, DESCRIPTION, QUANTITY, UNIT_PRICE)
        VALUES (v_invoice1_id, 'Minibar charges', 2, 25.00);

        INSERT INTO PAYMENTS (INVOICE_ID, AMOUNT, PAYMENT_METHOD, REFERENCE_NUMBER, RECEIVED_BY)
        VALUES (v_invoice1_id, 290.00, 'CARD', 'TXN-2026-001', v_recep_id);

        UPDATE ROOMS SET STATUS = 'AVAILABLE' WHERE ROOM_ID = v_room_201_id;
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN NULL;
    END;

    -- ============================================================
    -- SCENARIO 2: Active stay (Maria Garcia - currently checked in)
    -- Reservation -> Booking -> Check-in -> Partial payment
    -- ============================================================
    BEGIN
        INSERT INTO RESERVATIONS (GUEST_ID, ROOM_TYPE_ID, CHECK_IN_DATE, CHECK_OUT_DATE, STATUS, SPECIAL_REQUESTS, CREATED_BY)
        VALUES (v_guest2_id, 2, SYSDATE - 1, SYSDATE + 2, 'CHECKED_IN', 'Late check-out requested', v_recep_id)
        RETURNING RESERVATION_ID INTO v_reservation2_id;

        INSERT INTO BOOKINGS (RESERVATION_ID, ROOM_ID, CHECK_IN_DATE, CHECK_OUT_DATE, RATE_PER_NIGHT, STATUS)
        VALUES (v_reservation2_id, v_room_301_id, SYSDATE - 1, SYSDATE + 2, 150.00, 'ACTIVE')
        RETURNING BOOKING_ID INTO v_booking2_id;

        INSERT INTO CHECKINS (BOOKING_ID, CHECKED_IN_BY, NOTES)
        VALUES (v_booking2_id, v_recep_id, 'Guest checked in early, room ready')
        RETURNING CHECKIN_ID INTO v_checkin1_id;

        INSERT INTO INVOICES (BOOKING_ID, GUEST_ID, STATUS)
        VALUES (v_booking2_id, v_guest2_id, 'PARTIALLY_PAID')
        RETURNING INVOICE_ID INTO v_invoice2_id;

        INSERT INTO INVOICE_ITEMS (INVOICE_ID, DESCRIPTION, QUANTITY, UNIT_PRICE)
        VALUES (v_invoice2_id, 'Room 301 - Deluxe (3 nights)', 1, 450.00);

        INSERT INTO PAYMENTS (INVOICE_ID, AMOUNT, PAYMENT_METHOD, REFERENCE_NUMBER, RECEIVED_BY)
        VALUES (v_invoice2_id, 200.00, 'CASH', 'CASH-2026-001', v_recep_id);

        UPDATE ROOMS SET STATUS = 'OCCUPIED' WHERE ROOM_ID = v_room_301_id;
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN NULL;
    END;

    -- ============================================================
    -- SCENARIO 3: Upcoming reservation (Takeshi Yamamoto - confirmed, not yet checked in)
    -- Reservation only (no booking yet, room assigned at check-in)
    -- ============================================================
    BEGIN
        INSERT INTO RESERVATIONS (GUEST_ID, ROOM_TYPE_ID, CHECK_IN_DATE, CHECK_OUT_DATE, STATUS, SPECIAL_REQUESTS, CREATED_BY)
        VALUES (v_guest3_id, 3, SYSDATE + 3, SYSDATE + 7, 'CONFIRMED', 'Airport pickup arranged, suite with extra pillows', v_admin_id)
        RETURNING RESERVATION_ID INTO v_reservation3_id;
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN NULL;
    END;

    COMMIT;
END;
/

-- ============================================================
-- VERIFICATION
-- ============================================================
-- Run these to verify seed data:
--
-- SELECT 'ROLES' AS TAB, COUNT(*) AS CNT FROM ROLES
-- UNION ALL SELECT 'ROOM_TYPES', COUNT(*) FROM ROOM_TYPES
-- UNION ALL SELECT 'ROOMS', COUNT(*) FROM ROOMS
-- UNION ALL SELECT 'USERS', COUNT(*) FROM USERS
-- UNION ALL SELECT 'GUESTS', COUNT(*) FROM GUESTS
-- UNION ALL SELECT 'RESERVATIONS', COUNT(*) FROM RESERVATIONS
-- UNION ALL SELECT 'BOOKINGS', COUNT(*) FROM BOOKINGS
-- UNION ALL SELECT 'CHECKINS', COUNT(*) FROM CHECKINS
-- UNION ALL SELECT 'CHECKOUTS', COUNT(*) FROM CHECKOUTS
-- UNION ALL SELECT 'INVOICES', COUNT(*) FROM INVOICES
-- UNION ALL SELECT 'INVOICE_ITEMS', COUNT(*) FROM INVOICE_ITEMS
-- UNION ALL SELECT 'PAYMENTS', COUNT(*) FROM PAYMENTS;
