-- ============================================================
-- ALTONSHOTEL Management System
-- Seed Migration Version: 002
-- Description: Seed data for STAFF, PAYROLL, MAINTENANCE,
--              SYSTEM_SETTINGS tables
-- Safe to re-run (uses MERGE statements)
-- ============================================================

-- ============================================================
-- SYSTEM_SETTINGS
-- ============================================================
MERGE INTO SYSTEM_SETTINGS t
USING (SELECT 'hotel_name' AS SETTING_KEY, 'Altons Hotel' AS SETTING_VALUE, 'Hotel display name' AS DESCRIPTION, 1 AS UPDATED_BY FROM DUAL) s
ON (t.SETTING_KEY = s.SETTING_KEY)
WHEN NOT MATCHED THEN INSERT (SETTING_KEY, SETTING_VALUE, DESCRIPTION, UPDATED_BY) VALUES (s.SETTING_KEY, s.SETTING_VALUE, s.DESCRIPTION, s.UPDATED_BY);

MERGE INTO SYSTEM_SETTINGS t
USING (SELECT 'hotel_address' AS SETTING_KEY, '123 Main Street, City' AS SETTING_VALUE, 'Hotel address' AS DESCRIPTION, 1 AS UPDATED_BY FROM DUAL) s
ON (t.SETTING_KEY = s.SETTING_KEY)
WHEN NOT MATCHED THEN INSERT (SETTING_KEY, SETTING_VALUE, DESCRIPTION, UPDATED_BY) VALUES (s.SETTING_KEY, s.SETTING_VALUE, s.DESCRIPTION, s.UPDATED_BY);

MERGE INTO SYSTEM_SETTINGS t
USING (SELECT 'hotel_phone' AS SETTING_KEY, '+1-555-0100' AS SETTING_VALUE, 'Main phone number' AS DESCRIPTION, 1 AS UPDATED_BY FROM DUAL) s
ON (t.SETTING_KEY = s.SETTING_KEY)
WHEN NOT MATCHED THEN INSERT (SETTING_KEY, SETTING_VALUE, DESCRIPTION, UPDATED_BY) VALUES (s.SETTING_KEY, s.SETTING_VALUE, s.DESCRIPTION, s.UPDATED_BY);

MERGE INTO SYSTEM_SETTINGS t
USING (SELECT 'hotel_email' AS SETTING_KEY, 'info@altonshotel.com' AS SETTING_VALUE, 'Contact email' AS DESCRIPTION, 1 AS UPDATED_BY FROM DUAL) s
ON (t.SETTING_KEY = s.SETTING_KEY)
WHEN NOT MATCHED THEN INSERT (SETTING_KEY, SETTING_VALUE, DESCRIPTION, UPDATED_BY) VALUES (s.SETTING_KEY, s.SETTING_VALUE, s.DESCRIPTION, s.UPDATED_BY);

MERGE INTO SYSTEM_SETTINGS t
USING (SELECT 'tax_rate' AS SETTING_KEY, '10' AS SETTING_VALUE, 'Default tax rate (%)' AS DESCRIPTION, 1 AS UPDATED_BY FROM DUAL) s
ON (t.SETTING_KEY = s.SETTING_KEY)
WHEN NOT MATCHED THEN INSERT (SETTING_KEY, SETTING_VALUE, DESCRIPTION, UPDATED_BY) VALUES (s.SETTING_KEY, s.SETTING_VALUE, s.DESCRIPTION, s.UPDATED_BY);

MERGE INTO SYSTEM_SETTINGS t
USING (SELECT 'currency' AS SETTING_KEY, 'USD' AS SETTING_VALUE, 'Default currency' AS DESCRIPTION, 1 AS UPDATED_BY FROM DUAL) s
ON (t.SETTING_KEY = s.SETTING_KEY)
WHEN NOT MATCHED THEN INSERT (SETTING_KEY, SETTING_VALUE, DESCRIPTION, UPDATED_BY) VALUES (s.SETTING_KEY, s.SETTING_VALUE, s.DESCRIPTION, s.UPDATED_BY);

MERGE INTO SYSTEM_SETTINGS t
USING (SELECT 'check_in_time' AS SETTING_KEY, '14:00' AS SETTING_VALUE, 'Standard check-in time' AS DESCRIPTION, 1 AS UPDATED_BY FROM DUAL) s
ON (t.SETTING_KEY = s.SETTING_KEY)
WHEN NOT MATCHED THEN INSERT (SETTING_KEY, SETTING_VALUE, DESCRIPTION, UPDATED_BY) VALUES (s.SETTING_KEY, s.SETTING_VALUE, s.DESCRIPTION, s.UPDATED_BY);

MERGE INTO SYSTEM_SETTINGS t
USING (SELECT 'check_out_time' AS SETTING_KEY, '12:00' AS SETTING_VALUE, 'Standard check-out time' AS DESCRIPTION, 1 AS UPDATED_BY FROM DUAL) s
ON (t.SETTING_KEY = s.SETTING_KEY)
WHEN NOT MATCHED THEN INSERT (SETTING_KEY, SETTING_VALUE, DESCRIPTION, UPDATED_BY) VALUES (s.SETTING_KEY, s.SETTING_VALUE, s.DESCRIPTION, s.UPDATED_BY);

MERGE INTO SYSTEM_SETTINGS t
USING (SELECT 'max_guests_per_booking' AS SETTING_KEY, '4' AS SETTING_VALUE, 'Maximum guests per booking' AS DESCRIPTION, 1 AS UPDATED_BY FROM DUAL) s
ON (t.SETTING_KEY = s.SETTING_KEY)
WHEN NOT MATCHED THEN INSERT (SETTING_KEY, SETTING_VALUE, DESCRIPTION, UPDATED_BY) VALUES (s.SETTING_KEY, s.SETTING_VALUE, s.DESCRIPTION, s.UPDATED_BY);

MERGE INTO SYSTEM_SETTINGS t
USING (SELECT 'cancellation_policy' AS SETTING_KEY, 'Free cancellation 48 hours before check-in' AS SETTING_VALUE, 'Cancellation policy text' AS DESCRIPTION, 1 AS UPDATED_BY FROM DUAL) s
ON (t.SETTING_KEY = s.SETTING_KEY)
WHEN NOT MATCHED THEN INSERT (SETTING_KEY, SETTING_VALUE, DESCRIPTION, UPDATED_BY) VALUES (s.SETTING_KEY, s.SETTING_VALUE, s.DESCRIPTION, s.UPDATED_BY);

-- ============================================================
-- MAINTENANCE
-- ============================================================
DECLARE
    v_room_103_id NUMBER;
    v_room_501_id NUMBER;
    v_room_302_id NUMBER;
BEGIN
    SELECT ROOM_ID INTO v_room_103_id FROM ROOMS WHERE ROOM_NUMBER = '103';
    SELECT ROOM_ID INTO v_room_501_id FROM ROOMS WHERE ROOM_NUMBER = '501';
    SELECT ROOM_ID INTO v_room_302_id FROM ROOMS WHERE ROOM_NUMBER = '302';

    MERGE INTO MAINTENANCE t
    USING (SELECT 1 AS ID, v_room_103_id AS ROOM_ID, 'PLUMBING' AS ISSUE_TYPE, 'Leaking faucet in bathroom sink' AS DESCRIPTION, 'OPEN' AS STATUS, CURRENT_TIMESTAMP AS CREATED_DATE, 'Mike Plumber' AS ASSIGNED_TO, NULL AS RESOLVED_DATE, '' AS NOTES FROM DUAL) s
    ON (t.ID = s.ID)
    WHEN NOT MATCHED THEN INSERT (ROOM_ID, ISSUE_TYPE, DESCRIPTION, STATUS, CREATED_DATE, ASSIGNED_TO, RESOLVED_DATE, NOTES) VALUES (s.ROOM_ID, s.ISSUE_TYPE, s.DESCRIPTION, s.STATUS, s.CREATED_DATE, s.ASSIGNED_TO, s.RESOLVED_DATE, s.NOTES);

    MERGE INTO MAINTENANCE t
    USING (SELECT 2 AS ID, v_room_501_id AS ROOM_ID, 'ELECTRICAL' AS ISSUE_TYPE, 'Light fixture not working in bedroom' AS DESCRIPTION, 'IN_PROGRESS' AS STATUS, CURRENT_TIMESTAMP AS CREATED_DATE, 'Jane Electrician' AS ASSIGNED_TO, NULL AS RESOLVED_DATE, '' AS NOTES FROM DUAL) s
    ON (t.ID = s.ID)
    WHEN NOT MATCHED THEN INSERT (ROOM_ID, ISSUE_TYPE, DESCRIPTION, STATUS, CREATED_DATE, ASSIGNED_TO, RESOLVED_DATE, NOTES) VALUES (s.ROOM_ID, s.ISSUE_TYPE, s.DESCRIPTION, s.STATUS, s.CREATED_DATE, s.ASSIGNED_TO, s.RESOLVED_DATE, s.NOTES);

    MERGE INTO MAINTENANCE t
    USING (SELECT 3 AS ID, v_room_302_id AS ROOM_ID, 'HVAC' AS ISSUE_TYPE, 'AC unit making strange noise' AS DESCRIPTION, 'OPEN' AS STATUS, CURRENT_TIMESTAMP AS CREATED_DATE, 'Bob HVAC' AS ASSIGNED_TO, NULL AS RESOLVED_DATE, '' AS NOTES FROM DUAL) s
    ON (t.ID = s.ID)
    WHEN NOT MATCHED THEN INSERT (ROOM_ID, ISSUE_TYPE, DESCRIPTION, STATUS, CREATED_DATE, ASSIGNED_TO, RESOLVED_DATE, NOTES) VALUES (s.ROOM_ID, s.ISSUE_TYPE, s.DESCRIPTION, s.STATUS, s.CREATED_DATE, s.ASSIGNED_TO, s.RESOLVED_DATE, s.NOTES);
END;
/

-- ============================================================
-- STAFF
-- ============================================================
MERGE INTO STAFF t
USING (SELECT 'Alice Manager' AS FULL_NAME, 'alice@altonshotel.com' AS EMAIL, '+1-555-0201' AS PHONE, 'Management' AS DEPARTMENT, 'Front Desk Manager' AS POSITION, 45000 AS SALARY, DATE '2025-01-15' AS HIRE_DATE, 1 AS IS_ACTIVE FROM DUAL) s
ON (t.EMAIL = s.EMAIL)
WHEN NOT MATCHED THEN INSERT (FULL_NAME, EMAIL, PHONE, DEPARTMENT, POSITION, SALARY, HIRE_DATE, IS_ACTIVE) VALUES (s.FULL_NAME, s.EMAIL, s.PHONE, s.DEPARTMENT, s.POSITION, s.SALARY, s.HIRE_DATE, s.IS_ACTIVE);

MERGE INTO STAFF t
USING (SELECT 'Bob Receptionist' AS FULL_NAME, 'bob@altonshotel.com' AS EMAIL, '+1-555-0202' AS PHONE, 'Front Desk' AS DEPARTMENT, 'Receptionist' AS POSITION, 32000 AS SALARY, DATE '2025-03-01' AS HIRE_DATE, 1 AS IS_ACTIVE FROM DUAL) s
ON (t.EMAIL = s.EMAIL)
WHEN NOT MATCHED THEN INSERT (FULL_NAME, EMAIL, PHONE, DEPARTMENT, POSITION, SALARY, HIRE_DATE, IS_ACTIVE) VALUES (s.FULL_NAME, s.EMAIL, s.PHONE, s.DEPARTMENT, s.POSITION, s.SALARY, s.HIRE_DATE, s.IS_ACTIVE);

MERGE INTO STAFF t
USING (SELECT 'Carol Housekeeper' AS FULL_NAME, 'carol@altonshotel.com' AS EMAIL, '+1-555-0203' AS PHONE, 'Housekeeping' AS DEPARTMENT, 'Housekeeper' AS POSITION, 28000 AS SALARY, DATE '2025-02-10' AS HIRE_DATE, 1 AS IS_ACTIVE FROM DUAL) s
ON (t.EMAIL = s.EMAIL)
WHEN NOT MATCHED THEN INSERT (FULL_NAME, EMAIL, PHONE, DEPARTMENT, POSITION, SALARY, HIRE_DATE, IS_ACTIVE) VALUES (s.FULL_NAME, s.EMAIL, s.PHONE, s.DEPARTMENT, s.POSITION, s.SALARY, s.HIRE_DATE, s.IS_ACTIVE);

MERGE INTO STAFF t
USING (SELECT 'Dave Maintenance' AS FULL_NAME, 'dave@altonshotel.com' AS EMAIL, '+1-555-0204' AS PHONE, 'Maintenance' AS DEPARTMENT, 'Maintenance Technician' AS POSITION, 30000 AS SALARY, DATE '2025-04-20' AS HIRE_DATE, 1 AS IS_ACTIVE FROM DUAL) s
ON (t.EMAIL = s.EMAIL)
WHEN NOT MATCHED THEN INSERT (FULL_NAME, EMAIL, PHONE, DEPARTMENT, POSITION, SALARY, HIRE_DATE, IS_ACTIVE) VALUES (s.FULL_NAME, s.EMAIL, s.PHONE, s.DEPARTMENT, s.POSITION, s.SALARY, s.HIRE_DATE, s.IS_ACTIVE);

MERGE INTO STAFF t
USING (SELECT 'Eve Concierge' AS FULL_NAME, 'eve@altonshotel.com' AS EMAIL, '+1-555-0205' AS PHONE, 'Concierge' AS DEPARTMENT, 'Concierge' AS POSITION, 35000 AS SALARY, DATE '2025-05-05' AS HIRE_DATE, 1 AS IS_ACTIVE FROM DUAL) s
ON (t.EMAIL = s.EMAIL)
WHEN NOT MATCHED THEN INSERT (FULL_NAME, EMAIL, PHONE, DEPARTMENT, POSITION, SALARY, HIRE_DATE, IS_ACTIVE) VALUES (s.FULL_NAME, s.EMAIL, s.PHONE, s.DEPARTMENT, s.POSITION, s.SALARY, s.HIRE_DATE, s.IS_ACTIVE);

-- ============================================================
-- PAYROLL
-- ============================================================
DECLARE
    v_alice_id NUMBER;
    v_bob_id NUMBER;
    v_carol_id NUMBER;
    v_dave_id NUMBER;
    v_eve_id NUMBER;
BEGIN
    SELECT ID INTO v_alice_id FROM STAFF WHERE EMAIL = 'alice@altonshotel.com';
    SELECT ID INTO v_bob_id FROM STAFF WHERE EMAIL = 'bob@altonshotel.com';
    SELECT ID INTO v_carol_id FROM STAFF WHERE EMAIL = 'carol@altonshotel.com';
    SELECT ID INTO v_dave_id FROM STAFF WHERE EMAIL = 'dave@altonshotel.com';
    SELECT ID INTO v_eve_id FROM STAFF WHERE EMAIL = 'eve@altonshotel.com';

    MERGE INTO PAYROLL t
    USING (SELECT 1 AS ID, v_alice_id AS STAFF_ID, '2026-05' AS MONTH, 3750 AS SALARY_PAID, DATE '2026-05-31' AS PAYMENT_DATE FROM DUAL) s
    ON (t.ID = s.ID) WHEN NOT MATCHED THEN INSERT (STAFF_ID, MONTH, SALARY_PAID, PAYMENT_DATE) VALUES (s.STAFF_ID, s.MONTH, s.SALARY_PAID, s.PAYMENT_DATE);

    MERGE INTO PAYROLL t
    USING (SELECT 2 AS ID, v_alice_id AS STAFF_ID, '2026-06' AS MONTH, 3750 AS SALARY_PAID, DATE '2026-06-30' AS PAYMENT_DATE FROM DUAL) s
    ON (t.ID = s.ID) WHEN NOT MATCHED THEN INSERT (STAFF_ID, MONTH, SALARY_PAID, PAYMENT_DATE) VALUES (s.STAFF_ID, s.MONTH, s.SALARY_PAID, s.PAYMENT_DATE);

    MERGE INTO PAYROLL t
    USING (SELECT 3 AS ID, v_alice_id AS STAFF_ID, '2026-07' AS MONTH, 3750 AS SALARY_PAID, DATE '2026-07-31' AS PAYMENT_DATE FROM DUAL) s
    ON (t.ID = s.ID) WHEN NOT MATCHED THEN INSERT (STAFF_ID, MONTH, SALARY_PAID, PAYMENT_DATE) VALUES (s.STAFF_ID, s.MONTH, s.SALARY_PAID, s.PAYMENT_DATE);

    MERGE INTO PAYROLL t
    USING (SELECT 4 AS ID, v_bob_id AS STAFF_ID, '2026-05' AS MONTH, 2667 AS SALARY_PAID, DATE '2026-05-31' AS PAYMENT_DATE FROM DUAL) s
    ON (t.ID = s.ID) WHEN NOT MATCHED THEN INSERT (STAFF_ID, MONTH, SALARY_PAID, PAYMENT_DATE) VALUES (s.STAFF_ID, s.MONTH, s.SALARY_PAID, s.PAYMENT_DATE);

    MERGE INTO PAYROLL t
    USING (SELECT 5 AS ID, v_bob_id AS STAFF_ID, '2026-06' AS MONTH, 2667 AS SALARY_PAID, DATE '2026-06-30' AS PAYMENT_DATE FROM DUAL) s
    ON (t.ID = s.ID) WHEN NOT MATCHED THEN INSERT (STAFF_ID, MONTH, SALARY_PAID, PAYMENT_DATE) VALUES (s.STAFF_ID, s.MONTH, s.SALARY_PAID, s.PAYMENT_DATE);

    MERGE INTO PAYROLL t
    USING (SELECT 6 AS ID, v_bob_id AS STAFF_ID, '2026-07' AS MONTH, 2667 AS SALARY_PAID, DATE '2026-07-31' AS PAYMENT_DATE FROM DUAL) s
    ON (t.ID = s.ID) WHEN NOT MATCHED THEN INSERT (STAFF_ID, MONTH, SALARY_PAID, PAYMENT_DATE) VALUES (s.STAFF_ID, s.MONTH, s.SALARY_PAID, s.PAYMENT_DATE);

    MERGE INTO PAYROLL t
    USING (SELECT 7 AS ID, v_carol_id AS STAFF_ID, '2026-05' AS MONTH, 2333 AS SALARY_PAID, DATE '2026-05-31' AS PAYMENT_DATE FROM DUAL) s
    ON (t.ID = s.ID) WHEN NOT MATCHED THEN INSERT (STAFF_ID, MONTH, SALARY_PAID, PAYMENT_DATE) VALUES (s.STAFF_ID, s.MONTH, s.SALARY_PAID, s.PAYMENT_DATE);

    MERGE INTO PAYROLL t
    USING (SELECT 8 AS ID, v_carol_id AS STAFF_ID, '2026-06' AS MONTH, 2333 AS SALARY_PAID, DATE '2026-06-30' AS PAYMENT_DATE FROM DUAL) s
    ON (t.ID = s.ID) WHEN NOT MATCHED THEN INSERT (STAFF_ID, MONTH, SALARY_PAID, PAYMENT_DATE) VALUES (s.STAFF_ID, s.MONTH, s.SALARY_PAID, s.PAYMENT_DATE);

    MERGE INTO PAYROLL t
    USING (SELECT 9 AS ID, v_carol_id AS STAFF_ID, '2026-07' AS MONTH, 2333 AS SALARY_PAID, DATE '2026-07-31' AS PAYMENT_DATE FROM DUAL) s
    ON (t.ID = s.ID) WHEN NOT MATCHED THEN INSERT (STAFF_ID, MONTH, SALARY_PAID, PAYMENT_DATE) VALUES (s.STAFF_ID, s.MONTH, s.SALARY_PAID, s.PAYMENT_DATE);

    MERGE INTO PAYROLL t
    USING (SELECT 10 AS ID, v_dave_id AS STAFF_ID, '2026-06' AS MONTH, 2500 AS SALARY_PAID, DATE '2026-06-30' AS PAYMENT_DATE FROM DUAL) s
    ON (t.ID = s.ID) WHEN NOT MATCHED THEN INSERT (STAFF_ID, MONTH, SALARY_PAID, PAYMENT_DATE) VALUES (s.STAFF_ID, s.MONTH, s.SALARY_PAID, s.PAYMENT_DATE);

    MERGE INTO PAYROLL t
    USING (SELECT 11 AS ID, v_dave_id AS STAFF_ID, '2026-07' AS MONTH, 2500 AS SALARY_PAID, DATE '2026-07-31' AS PAYMENT_DATE FROM DUAL) s
    ON (t.ID = s.ID) WHEN NOT MATCHED THEN INSERT (STAFF_ID, MONTH, SALARY_PAID, PAYMENT_DATE) VALUES (s.STAFF_ID, s.MONTH, s.SALARY_PAID, s.PAYMENT_DATE);

    MERGE INTO PAYROLL t
    USING (SELECT 12 AS ID, v_eve_id AS STAFF_ID, '2026-06' AS MONTH, 2917 AS SALARY_PAID, DATE '2026-06-30' AS PAYMENT_DATE FROM DUAL) s
    ON (t.ID = s.ID) WHEN NOT MATCHED THEN INSERT (STAFF_ID, MONTH, SALARY_PAID, PAYMENT_DATE) VALUES (s.STAFF_ID, s.MONTH, s.SALARY_PAID, s.PAYMENT_DATE);

    MERGE INTO PAYROLL t
    USING (SELECT 13 AS ID, v_eve_id AS STAFF_ID, '2026-07' AS MONTH, 2917 AS SALARY_PAID, DATE '2026-07-31' AS PAYMENT_DATE FROM DUAL) s
    ON (t.ID = s.ID) WHEN NOT MATCHED THEN INSERT (STAFF_ID, MONTH, SALARY_PAID, PAYMENT_DATE) VALUES (s.STAFF_ID, s.MONTH, s.SALARY_PAID, s.PAYMENT_DATE);
END;
/

COMMIT;
