-- ============================================================
-- ALTONSHOTEL Management System
-- Database Schema Version: 002
-- Description: Initial schema creation with production hardening
-- Author: AHMS Development Team
-- Date: 2026-07-27
--
-- Run this script ONCE on a fresh Oracle database.
-- For seed data, run database/migrations/001_idempotent_seed.sql
-- ============================================================

-- ============================================================
-- ROLES
-- ============================================================
CREATE TABLE ROLES (
    ROLE_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ROLE_NAME     VARCHAR2(50) NOT NULL UNIQUE,
    DESCRIPTION   VARCHAR2(200),
    CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- USERS
-- ============================================================
CREATE TABLE USERS (
    USER_ID             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME            VARCHAR2(50) NOT NULL UNIQUE,
    PASSWORD_HASH       VARCHAR2(255) NOT NULL,
    FULL_NAME           VARCHAR2(100) NOT NULL,
    EMAIL               VARCHAR2(100) NOT NULL UNIQUE,
    ROLE_ID             NUMBER NOT NULL,
    IS_ACTIVE           NUMBER(1) DEFAULT 1,
    FAILED_LOGIN_ATTEMPTS NUMBER(2) DEFAULT 0,
    LAST_LOGIN          TIMESTAMP,
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_USERS_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID)
);

-- ============================================================
-- ROOM TYPES
-- ============================================================
CREATE TABLE ROOM_TYPES (
    TYPE_ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TYPE_NAME       VARCHAR2(50) NOT NULL UNIQUE,
    DESCRIPTION     VARCHAR2(500),
    BASE_PRICE      NUMBER(10,2) NOT NULL,
    MAX_OCCUPANCY   NUMBER(2) NOT NULL,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- ROOMS
-- ============================================================
CREATE TABLE ROOMS (
    ROOM_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ROOM_NUMBER   VARCHAR2(10) NOT NULL UNIQUE,
    TYPE_ID       NUMBER NOT NULL,
    FLOOR         NUMBER(2) NOT NULL CHECK (FLOOR >= 1),
    STATUS        VARCHAR2(20) DEFAULT 'AVAILABLE'
                  CHECK (STATUS IN ('AVAILABLE','OCCUPIED','MAINTENANCE','RESERVED')),
    DESCRIPTION   VARCHAR2(500),
    CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ROOMS_TYPE FOREIGN KEY (TYPE_ID) REFERENCES ROOM_TYPES(TYPE_ID)
);

-- ============================================================
-- GUESTS
-- ============================================================
CREATE TABLE GUESTS (
    GUEST_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FIRST_NAME    VARCHAR2(50) NOT NULL,
    LAST_NAME     VARCHAR2(50) NOT NULL,
    EMAIL         VARCHAR2(100),
    PHONE         VARCHAR2(20) NOT NULL,
    ID_TYPE       VARCHAR2(30) NOT NULL
                  CHECK (ID_TYPE IN ('PASSPORT','NATIONAL_ID','DRIVERS_LICENSE','OTHER')),
    ID_NUMBER     VARCHAR2(50) NOT NULL,
    ADDRESS       VARCHAR2(300),
    NATIONALITY   VARCHAR2(50),
    CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- RESERVATIONS
-- ============================================================
CREATE TABLE RESERVATIONS (
    RESERVATION_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    GUEST_ID          NUMBER NOT NULL,
    ROOM_TYPE_ID      NUMBER NOT NULL,
    CHECK_IN_DATE     DATE NOT NULL,
    CHECK_OUT_DATE    DATE NOT NULL,
    STATUS            VARCHAR2(20) DEFAULT 'PENDING'
                      CHECK (STATUS IN ('PENDING','CONFIRMED','CANCELLED','CHECKED_IN','COMPLETED')),
    SPECIAL_REQUESTS  VARCHAR2(1000),
    CREATED_BY        NUMBER NOT NULL,
    CREATED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_RESERVATIONS_GUEST FOREIGN KEY (GUEST_ID) REFERENCES GUESTS(GUEST_ID),
    CONSTRAINT FK_RESERVATIONS_ROOM_TYPE FOREIGN KEY (ROOM_TYPE_ID) REFERENCES ROOM_TYPES(TYPE_ID),
    CONSTRAINT FK_RESERVATIONS_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(USER_ID),
    CONSTRAINT CHK_RESERVATION_DATES CHECK (CHECK_OUT_DATE > CHECK_IN_DATE)
);

-- ============================================================
-- BOOKINGS
-- ============================================================
CREATE TABLE BOOKINGS (
    BOOKING_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RESERVATION_ID  NUMBER NOT NULL,
    ROOM_ID         NUMBER NOT NULL,
    CHECK_IN_DATE   DATE NOT NULL,
    CHECK_OUT_DATE  DATE NOT NULL,
    RATE_PER_NIGHT  NUMBER(10,2) NOT NULL,
    STATUS          VARCHAR2(20) DEFAULT 'ACTIVE'
                    CHECK (STATUS IN ('ACTIVE','COMPLETED','CANCELLED')),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_BOOKINGS_RESERVATION FOREIGN KEY (RESERVATION_ID) REFERENCES RESERVATIONS(RESERVATION_ID),
    CONSTRAINT FK_BOOKINGS_ROOM FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ROOM_ID),
    CONSTRAINT CHK_BOOKING_DATES CHECK (CHECK_OUT_DATE > CHECK_IN_DATE)
);

-- ============================================================
-- CHECKINS
-- ============================================================
CREATE TABLE CHECKINS (
    CHECKIN_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BOOKING_ID       NUMBER NOT NULL UNIQUE,
    ACTUAL_CHECK_IN  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CHECKED_IN_BY    NUMBER NOT NULL,
    NOTES            VARCHAR2(500),
    CONSTRAINT FK_CHECKINS_BOOKING FOREIGN KEY (BOOKING_ID) REFERENCES BOOKINGS(BOOKING_ID),
    CONSTRAINT FK_CHECKINS_USER FOREIGN KEY (CHECKED_IN_BY) REFERENCES USERS(USER_ID)
);

-- ============================================================
-- CHECKOUTS
-- ============================================================
CREATE TABLE CHECKOUTS (
    CHECKOUT_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CHECKIN_ID       NUMBER NOT NULL UNIQUE,
    ACTUAL_CHECK_OUT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CHECKED_OUT_BY   NUMBER NOT NULL,
    NOTES            VARCHAR2(500),
    CONSTRAINT FK_CHECKOUTS_CHECKIN FOREIGN KEY (CHECKIN_ID) REFERENCES CHECKINS(CHECKIN_ID),
    CONSTRAINT FK_CHECKOUTS_USER FOREIGN KEY (CHECKED_OUT_BY) REFERENCES USERS(USER_ID)
);

-- ============================================================
-- INVOICES
-- ============================================================
CREATE TABLE INVOICES (
    INVOICE_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BOOKING_ID     NUMBER NOT NULL,
    GUEST_ID       NUMBER NOT NULL,
    TOTAL_AMOUNT   NUMBER(12,2) DEFAULT 0 NOT NULL,
    STATUS         VARCHAR2(20) DEFAULT 'PENDING'
                   CHECK (STATUS IN ('PENDING','PAID','PARTIALLY_PAID','CANCELLED')),
    CREATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_INVOICES_BOOKING FOREIGN KEY (BOOKING_ID) REFERENCES BOOKINGS(BOOKING_ID),
    CONSTRAINT FK_INVOICES_GUEST FOREIGN KEY (GUEST_ID) REFERENCES GUESTS(GUEST_ID)
);

-- ============================================================
-- INVOICE ITEMS
-- ============================================================
CREATE TABLE INVOICE_ITEMS (
    ITEM_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    INVOICE_ID     NUMBER NOT NULL,
    DESCRIPTION    VARCHAR2(200) NOT NULL,
    QUANTITY       NUMBER(5) DEFAULT 1 NOT NULL,
    UNIT_PRICE     NUMBER(10,2) NOT NULL,
    TOTAL          NUMBER(12,2) GENERATED ALWAYS AS (QUANTITY * UNIT_PRICE) STORED,
    CONSTRAINT FK_INVOICE_ITEMS_INVOICE FOREIGN KEY (INVOICE_ID) REFERENCES INVOICES(INVOICE_ID)
);

-- ============================================================
-- PAYMENTS
-- ============================================================
CREATE TABLE PAYMENTS (
    PAYMENT_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    INVOICE_ID        NUMBER NOT NULL,
    AMOUNT            NUMBER(12,2) NOT NULL,
    PAYMENT_METHOD    VARCHAR2(20) NOT NULL
                      CHECK (PAYMENT_METHOD IN ('CASH','CARD','BANK_TRANSFER')),
    PAYMENT_DATE      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REFERENCE_NUMBER  VARCHAR2(100),
    RECEIVED_BY       NUMBER NOT NULL,
    CONSTRAINT FK_PAYMENTS_INVOICE FOREIGN KEY (INVOICE_ID) REFERENCES INVOICES(INVOICE_ID),
    CONSTRAINT FK_PAYMENTS_USER FOREIGN KEY (RECEIVED_BY) REFERENCES USERS(USER_ID)
);

-- ============================================================
-- AUDIT LOG
-- ============================================================
CREATE TABLE AUDIT_LOG (
    AUDIT_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TABLE_NAME    VARCHAR2(50) NOT NULL,
    RECORD_ID     NUMBER NOT NULL,
    ACTION        VARCHAR2(10) NOT NULL,
    CHANGES       VARCHAR2(4000),
    PERFORMED_BY  VARCHAR2(50),
    PERFORMED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- INDEXES
-- ============================================================
CREATE INDEX IDX_USERS_ROLE ON USERS(ROLE_ID);
CREATE INDEX IDX_ROOMS_STATUS ON ROOMS(STATUS);
CREATE INDEX IDX_ROOMS_TYPE ON ROOMS(TYPE_ID);
CREATE INDEX IDX_ROOMS_FLOOR ON ROOMS(FLOOR);
CREATE INDEX IDX_GUESTS_NAME ON GUESTS(LAST_NAME, FIRST_NAME);
CREATE INDEX IDX_GUESTS_PHONE ON GUESTS(PHONE);
CREATE INDEX IDX_RESERVATIONS_DATES ON RESERVATIONS(CHECK_IN_DATE, CHECK_OUT_DATE);
CREATE INDEX IDX_RESERVATIONS_STATUS ON RESERVATIONS(STATUS);
CREATE INDEX IDX_RESERVATIONS_GUEST ON RESERVATIONS(GUEST_ID);
CREATE INDEX IDX_BOOKINGS_DATES ON BOOKINGS(CHECK_IN_DATE, CHECK_OUT_DATE);
CREATE INDEX IDX_BOOKINGS_ROOM ON BOOKINGS(ROOM_ID);
CREATE INDEX IDX_BOOKINGS_RES_STATUS ON BOOKINGS(RESERVATION_ID, STATUS);
CREATE INDEX IDX_INVOICES_STATUS ON INVOICES(STATUS);
CREATE INDEX IDX_INVOICES_GUEST ON INVOICES(GUEST_ID);
CREATE INDEX IDX_INVOICES_BOOKING ON INVOICES(BOOKING_ID);
CREATE INDEX IDX_PAYMENTS_INVOICE ON PAYMENTS(INVOICE_ID);
CREATE INDEX IDX_AUDIT_TABLE ON AUDIT_LOG(TABLE_NAME);
CREATE INDEX IDX_AUDIT_DATE ON AUDIT_LOG(PERFORMED_AT);
